SAMPLE_COUNT = 8
MAX_BOOTSTRAP_ERRORS = 5
BOOTSTRAP_ITERATION_TIMEOUT = 2
FIND_ITERATION_TIMEOUT = 2
PEERS_ITERATION_TIMEOUT = 2
GC_ITERATION_TIMEOUT = 1
GC_MAX_TIME = 60
GX_MAX_TRANS = 5

RANDOMIZE_NODE_ID = False
RANDOM_FIND_PEERS = False
